### ISSUE TITLE
Traceback error when manually installed

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/color-sorting-cli#90] opened 2023-04-26 12:07 UTC
I tried to follow the manual installation but got the following Traceback, no matter what I try to run:

```
Traceback (most recent call last):
  File "/Users/adrian/Library/Python/3.11/bin/harmony", line 5, in <module>
    from harmony.harmony.main import app
  File "/Users/adrian/Library/Python/3.11/lib/python/site-packages/harmony/harmony/main.py", line 7, in <module>
    from harmony.color_sorting.commands import sort
  File "/Users/adrian/Library/Python/3.11/lib/python/site-packages/harmony/color_sorting/commands.py", line 6, in <module>
    from harmony import core, core_services
  File "/Users/adrian/Library/Python/3.11/lib/python/site-packages/harmony/core/__init__.py", line 1, in <module>
    from charmony import CIELAB, HSL, RGB, Color
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Please note I am using an arm64 build, on Apple Silicon.

**Comment by AdrianSimionov** [comment] 2023-04-27 09:56
Maybe give it a go in a Linux Docker arm64, might uncover the reason for it.

**Comment by xlurio** [comment] 2023-04-29 17:54
It worth trying, but the ELF file (linux) and the Mach-O file (MacOS), although both have the `.so` extension, are different files

**Comment by AdrianSimionov** [comment] 2023-07-07 00:52
Tried to install again using the arm64 and universal2 whl files and this issue persists on Apple Silicon M2.

**Comment by xlurio** [comment] 2023-07-13 17:13
Can you run the command `$ locale` in the Apple Silicon and show the output, please?

There was a [bug](https://bugs.python.org/issue41894) in the Python interpreters from the version 3.8+ where, if it failed to load the module, it would try to run the low-level function `PyUnicode_FromString` on the error message to show to the user. That would cause a `UnicodeDecodeError` for OSs which the locale encoding is not `UTF-8`. It apparently was fixed, but one of my hypothesis is that you are using an outdated Python interpreter which this bug persists.

**Comment by AdrianSimionov** [comment] 2023-07-14 08:21
```
❯ locale
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=
```

**Comment by xlurio** [comment] 2023-07-14 17:44
Can you please try running Harmony on Python 3.8? It could be due to some incompatibility due to the low level CPython API. If it works I'll rewrite the Harmony low level API to [Cython](https://github.com/cython/cython) so it transpile to C accordingly to the python version.

**Comment by xlurio** [comment] 2023-07-14 17:46
Also, can you run `$ pip list` to ensure the Harmony version is `1.2.0`?

**Comment by AdrianSimionov** [comment] 2023-07-15 04:59
> Can you please try running Harmony on Python 3.8? It could be due to some incompatibility due to the Python low level API. If it works I'll rewrite the Harmony low level API to [Cython](https://github.com/cython/cython) so it transpile to C accordingly to the python version.

Please provide the commands as I will not make python3.8 default version.

**Comment by xlurio** [comment] 2023-07-18 22:23
The pull request #107 might fix this error, but as I can't reproduce the error I can't be certain yet. We will see it in the friday release

**Comment by xlurio** [comment] 2023-08-08 12:55
Can you try again using the latest release?

**Comment by AdrianSimionov** [comment] 2023-08-09 03:30
Great news, this time works. I used Python 3.11 on arm64.

**Comment by xlurio** [comment] 2023-08-09 23:18
Good to know! Closing issue based on changes done in #107 then

**Closed by xlurio** 2023-08-09 23:18 UTC
Labels: bug, priority:high
